adds example to reproduce error "TypeError: __html.replace is not a function" to reproduce, do "npm run coverage" which will run and then invoke "postcoverage" which in turn calls ./setup/process-coverage-report.js, which is where the error happens you can then demonstrate that converting _html to String first resolves the issue by adding my updated list-stylesheets code to the dependencies with "list-stylesheets": "github:LCHarold/list-stylesheets#master"